pinojs/pino-http

logger.js
test.js

Reuse req.id if present

---

README.md
logger.js
test.js

Fixes #2 #7 
cc @marcbachmann @davidmarkclements

Reuse pino instance if passed with 'logger' option. Document the serializers

---

logger.js
test.js

Fixes https://github.com/pinojs/pino-http/issues/14

fix custom instance and custom request id

---

logger.js

…estId is faster than modulus by 7x on my Macbook Pro

Modified genReqId with quick, small performance boost.

---

logger.js
package.json
test.js

Reverts pinojs/pino-http#22
Fixes #24

Revert "Handle client abort and server timeout separatly."

---

package.json
scripts/benchmark
scripts/benchmark-all

This adds couple of scripts to make running benchmarks easier.

Add scripts for benchmarking

---

README.md

@Rauno56 does this explain it adequately?

startTime docs

---

README.md

This PR adds documentation that shows how to supply custom serializers. This should resolve issue #47.

Add example for custom serializer (resolve #47)

---

test.js

Hello! It's a tests refactoring which was requested in this issue https://github.com/pinojs/pino-http/issues/81

Rewrite all tests with timers

---

.travis.yml
logger.js
package.json
test.js

Updated dependencies

---

logger.js
package.json

Use the second positional argument for pino.child()

---

.github/workflows/ci.yml
README.md
benchmarks/http-ndjson-equivalent-server.js
benchmarks/http-ndjson-minimal-server.js
benchmarks/no-log-server.js
benchmarks/pino-extreme-server.js
benchmarks/pino-server.js
example.js
logger.js
package.json
test.js

This PR updates pino dependency to Pino 7.0.5.
It also changes all occurence of `var` to `const/let` as advised by `standard`.
Closes #172.

chore: Updated to pino 7.

---

README.md
example-custom-format.js
package.json
test/test.js
test/transport-integration.js

fixes https://github.com/pinojs/pino-http/issues/73
It is possible to get the desired output using the new pino 7 transport.
I have added an example with tests

add format example test

---

index.d.ts
index.test-d.ts

Exports interfaces and types in `index.d.ts`.
Relates to #181, #175

fix: type definition updates

---

README.md
index.d.ts
index.test-d.ts
logger.js
test/test.js

Fixes https://github.com/pinojs/pino-http/issues/208

Add req argument to custom success/error

---

logger.js
test/test.js

Support customLevels in useLevel/customLogLevel

---

.github/workflows/ci.yml
package.json

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Bumped pino@8

---

index.d.ts
index.test-d.ts

Hello! It's a fix for the https://github.com/pinojs/pino-http/issues/243
I'm participating in Hactoberfest 2022 so If you Ok with the changes could you please add a "HACKTOBERFEST-ACCEPTED" label to it.

update stdSerializers types

---

import.test-d.ts

test(types): explicitly declare semicolon

---

README.md

Update README.md with middleware example

---

README.md

fix: #291 added definition for id variable
