logger.js, test.js
The responseTime on a failed request didn't work anymore
=> Fix responseTime on errored request

README.md, logger.js, test.js
This adds a `opts.genReqId` option that can be a function that returns a custom request id.
@mcollina Did you have something like this in mind?
Tests are still missing
=> Support a custom requestId generation function

README.md, logger.js, test.js
Added the `stream` option to pass the destination stream inside the `options` object instead of the second parameter.
I left the standalone stream parameter for back compatibility.
(cc https://github.com/mcollina/fastify/pull/25)
=> Stream options

README.md, logger.js, test.js
I think it should be using the `debug` level by default, but I didn't want to introduce a breaking change.
=> Add useLevel option

logger.js, test.js
It's possible that requests takes so long that it's either aborted by the browser or by the http.Server.
In both cases, there is no log call saying that the connection is dead, which gives the feeling in the logs, that request is still in progress.
=> Print log for aborted connections

logger.js
hey,
this pull request adds `pino.stdSerializers.err` to the logger serializers.
is there a reason why this was not done before? maybe i'm naive and missing something obvious.
cheers!
=> use standard err serializer

logger.js, test.js
Sometimes it's not possible to attach logger in the very beginning of the request, unfortunately `pino-http` overwrites what's there for, what seems to me, no good reason.
=> Respect startTime if already defined

logger.js, test.js
While updating `restify-pino-logger` I learned that the request id property was not getting set properly. I'm don't know how it ever was. Consider:
1. https://github.com/pinojs/pino-http/blame/626eede60281e460e77968836293d671d709f19a/logger.js#L53
1. https://github.com/pinojs/pino-http/blame/626eede60281e460e77968836293d671d709f19a/logger.js#L82
First it's set to a function and then that function is assigned to the property.
This PR simply invokes the `req.id` function in the serializer if it is actually a function. Otherwise it assigns whatever that value is to the property.
=> Fix setting request id

logger.js, test.js
The `err` param in `onResFinished(err)` was always `undefined` no matter what the result of the request was.
From nodejs / express documentation, there is no event named `error`:
- https://expressjs.com/en/4x/api.html#res
- https://nodejs.org/api/http.html#http_class_http_serverresponse
The `res` object can be used as a the `err` holder, and set on the `res` object in the express error handler middleware 
```js
function onErrorMiddleware(err, req, res, next) {
res.err = err;
//code
}
```
If no `err` object on the response but a bad `statusCode`, we generate the error from the logger. I know this would show a somewhat confusing stack, but it's something. 
Besides the `stdSerializers.err` handles string error as an array of chars.
=> Fix request on error logger

logger.js, package.json
Remove code that is duplicated in the `pino-std-serializers` module.
=> Refactor to use pino-std-serializers

logger.js
The fallback error message didn't contain a space:
`"err":{"type":"Error","message":"failed with status code500",`
The updated message now looks like:
`"err":{"type":"Error","message":"failed with status code 500",`
=> Fix message formatting in request error fallback

README.md, logger.js, test.js
Adding a getUseLevel function that dynamically allows you to set the log level based on the status of the result and the error object (if any)
The change makes it possible to separate http errors from system errors.
For example, you can specify a user who types in an incorrect password will get an error with an HTTP 401 status, but the log level will be a warning rather than an error.
=> Add getUseLevel option

README.md, logger.js, package.json, test.js
Tests will fail initially b/c depends on https://github.com/pinojs/pino-std-serializers/pull/18. Will need to bump version of pino-std-serializers.
=> add support for wrapping the default error serializer

README.md
Adds an example for a common use case of wanting the request body logged.
=> Add log request body example

README.md, logger.js, package.json, test.js
I would like to push these changes to allow the library to ignore certain paths to autolog.
This is specially useful if I have a health check path which gets called every 3 seconds. If not ignored this would fill our logs a lot.
My first step is to push this in pino-http, then update koa-pino-logger, and I finally use it on my koa app.
One line that definitely needs feedback is on middleware, since the variable is currently called `_currentUrl` (it can improve) and also I did not have access to request on `onResFinished`.
Also I did not find access to the url's path alone, so I had to use raw url for now.
Well hope this can help and be accepted. I think it delivers a good functionality.
=> Add autologgingOptions to ignore certain paths like those for health checks.

README.md, logger.js, test.js
Hello, thanks for the awesome module!
This PR adds a new callback function `getPath` to the autoLogging options which allows implementers to supply a path when checking against `ignorePaths` instead of relying on the default `req.url`.
This issue came up when we tried to implement pino-http into our Nestjs application using the [nestjs-pino](https://github.com/iamolegga/nestjs-pino) library and found that due to how the middleware is injected express was stripping the `req.url` as [documented here](https://expressjs.com/en/api.html#req.originalUrl). This led me to believe the best way to get the functionality we needed was to allow the implementer to supply the current path as a callback function.
An example of how we would use this in our config.
```
{
autoLogging: {
ignorePaths: …
```
=> Add getPath option to autoLogging when req.url is not suitable for matching

.gitignore, README.md, logger.js, package.json, test.js
Adds a configuration option to rename the keys in the JSON log. Keys which can be renamed are `req`, `res`, `err`, and `responseTime`.
=> Option to override the log object key naming with custom values

README.md, logger.js, test.js
Fixes #95
Summary
1) Add `opts.wrapSerializers` to allow consumers to disable wrapping them with the standard serializers
- This importantly ensures serializers applied to `opts.logger` are not always overridden with the default serializers.
2) Avoid mutating `opts` and `opts.serializers`
=> [#95] Add option to prevent serializers from being wrapped

logger.js, test.js
Currently causing the tests to fail in express-pino-logger:
```text
not ok message is set
--- wanted                  
+++ found                   
-"request errored"          
+"request errored "         
```
=> Remove trailing space in error message

README.md, logger.js, test.js
**Feature Request:** Able to log additional properties outside `req` in the log line that depends on the request.
https://github.com/pinojs/pino-http/issues/102
A the moment, if one would like to log that is specific to the incoming http request it can only be logged within `req` object in the log line. This is can be achieved by having reqSerializer. 
Example:
```
{
host: 'xxx',
pid: 123,
req: { key1: val1, key2, val2}
}
```
But if you wish to log outside the `req` object, at the moment there is no way.
Eg:
```
{
host: 'xxx',
pid: 123,
req: { key1: val1},
{key2: val2}
}
```
Please review this feature request and provide feedback. 
Proposing a new option called  `reqCustomProps`  where one could do something like this
```
reqCustomProps: function (req) { 
return { customProp` : …
```
=> Feature Request: Able to log additional properties outside req in the log line

README.md, test.js
The Readme currently defines the `customErrorMessage` function as having the following signature:
```js
function (res, err) => { /* returns message  string */ }
```
However, the actual implementation
https://github.com/pinojs/pino-http/blob/d593aa6084f1fe70a506ad8f202fc7f339b87fb5/logger.js#L79
Uses `err, res`.
This changes fixes the Readme so that people can use it the right way.
I also added the error to the message in the test to show the use cases for it
I also removed the `package-lock.json` file from the `.gitignore` as that should be checked into source control. Please let me know if it's removed by design.
There is also an error in the `@types/pino-http` package added in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/770b1753b685c22a2a75309ed45058cd66159adb
I'll be …
=> Fix incorrect documentation for customErrorMessage 

logger.js, package.json, test.js
I was using the latest version and have a use-case where I want to ignore a dynamic range of paths that can change over time. In order to support this I thought that adding RegExp support to the ignoring mechanism might be an option.
Let me know what you think. Thanks for taking a look.
=> Support regex path matching for autoLogging.ignorePaths option

README.md, logger.js, package.json, test.js
Added `res` object as additional function parameter to the `reqCustomProps` function
Non-breaking now, but function name will need to be changed in next semver major update, will add PR after this is merged to reuse the branch.
Updated `README.md` and `test.js` with new function signature.
Side effects:
- had to add "bash" to beginning of benchmark command since it relies on bash, and errors out on systems where bash is not the default.
- added "fix" npm script since locally installed `standard` has to be run inside npm script to use local version, and `standard --fix` must be run to get tests to run.
closes #119
=> fix: add res to reqCustomProp function signature

README.md, logger.js, test.js
Since the function's name no longer accurately represents its new signature, whenever there are other breaking changes to be made to the interface, this would be a good semantic change to also include.
=> either reqCustomProps or customProps are valid

README.md
A missing newline made the stream documentation part of the last
bullet in the above bullet list.
Before fix:
After fix:
=> Fix README documentation typo for stream

README.md
As was discussed in https://github.com/pinojs/pino-http/issues/125, I've enhanced documentation a bit.
=> [Docs] details about `pinoHttp.logger` field

README.md, logger.js, test.js
solves #107 via a generic `autologging.ignore` function 
I get errors locally when trying to test: `Unexpected var, use let or const instead.`, linting fixes it (`npm run fix`) but have reverted the linting as requested
=> add autologging ignore option

index.d.ts, index.test-d.ts, package.json, tsconfig.json
=> Pino 7 Type Definition

README.md, index.d.ts, index.test-d.ts, logger.js, test/test.js
This PR begin from a specific need:
- Love autoLogging
- Love serializers
- Doesn't need health check logs
- Only needs logs for debug
- `Can I prevent autoLogging by Response status code?` **NO**
I just add an early return in the `onResFinished` method. When the `level`, coming either from `useLevel` or `customLogLevel` option, the method finishes early without calling the logger.
This PR doesn't have breaking changes.
resolve #190
=> Early return on silent level

logger.js
Improve the throughput of express by 25% with this simple change.
There is likely more to be done here to improve things.
Before:
```
$ autocannon -W [ -c 10 -d 2 ] -c 100 -p 10 -d 10 localhost:3000
Running 2s warmup @ http://localhost:3000
10 connections with 10 pipelining factor
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor
┌─────────┬────────┬────────┬────────┬────────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5%   │ 50%    │ 97.5%  │ 99%    │ Avg      │ Stdev    │ Max    │
├─────────┼────────┼────────┼────────┼────────┼──────────┼──────────┼────────┤
│ Latency │ 137 ms │ 143 ms │ 169 ms │ 178 ms │ 145.8 ms │ 14.37 ms │ 293 ms │
└─────────┴────────┴────────┴────────┴────────┴──────────┴──────────┴────────┘ …
```
=> 25% throughput improvement

logger.js, test/test.js
This PR fixes the issues with #168 and also fixes the regression it introduced where customProps wouldn't be set until the response was sent (if you were using customReceiveMessage or just any other logging on your server).
The downsides are the customProps gets called twice, but it feels worth it to me personally.
=> Give customProps access to the response

README.md, index.d.ts, logger.js, test/test.js
This adds a functionality for overriding/customising the structured object logged at request received/success/error. It is *like* the custom[Received|Success|Error]Message hooks, but works on customising the structured object.
It was opted not to overload *Message due to that being specifically about messages, and the risk that adjusting that could break an existing usage of that hook.
The README has been updated with example usage.
=> Add custom object hooks

README.md, logger.js, test/test.js
Passing the response body object to genReqId() allows us to more easily
share the request ID throughout our code, e.g. setting an “X-Request-Id”
header via “response.header()” or storing it in “response.locals” for
rendering.
=> Pass response object to genReqId()

index.d.ts, index.test-d.ts
=> fix(genreqid): add param for server response

logger.js, test/test.js
Fix https://github.com/pinojs/pino-http/issues/199
Please also add "hacktoberfest-accepted" label :)
=> Add success response time

.github/workflows/ci.yml, index.d.ts, index.test-d.ts, logger.js, test/test.js
PR to address Issue #260 
- scope pino loggers to lambda closures instead of function properties
- set request and response log property to first middleware pino logger but capture additional middleware pino loggers in new allLogs request and response property
- unit tests to confirm each middleware redact properties are independent
=> Feature: Allow multiple instances of middleware

index.d.ts, index.test-d.ts
according to API docs the error param in customLogLevel function is optional
but that is not reflected in the typescript definition
> customLogLevel: set to a function (req, res, err) => { /* returns level name string */ }. This function will be invoked to determine the level at which the log should be issued (silent will prevent logging). This option is mutually exclusive with the useLevel option. The first two arguments are the HTTP request and response. **The third argument is an error object if an error has occurred in the request**.
=> fix: set error param as optional for options.customLogLevel

import.test-d.ts, index.d.ts
https://github.com/pinojs/pino-http/pull/253 added `responseTime` value to be passed into the `customSuccessMessage` callback but the TS definition file was not updated.
=> Fix customSuccessMessage ts definition

logger.js, test/test.js
Hi!
I found a bug.
There is a missing `req` argument in `getLogLevelFromCustomLogLevel` function call [at onResFinished](https://github.com/pinojs/pino-http/blob/master/logger.js#L97)
Because of this, I got an error `TypeError: Cannot read properties of undefined (reading 'req')`, when using `customLogLevel` option
=> Fix customLogLevel usage in onResFinished function

README.md
The example in the docs assumes `expressjs` `req` and `res` arguments, but the types in the library assume vanilla `req` and `res`. There is no mention of minimum required NodeJS version so I assume it's at least 14+, which supports [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility).
=> docs(readme): fix genReqId() example

README.md
Changes the badge from this:
[![Build Status](https://img.shields.io/github/workflow/status/pinojs/pino-http/CI)](https://github.com/pinojs/pino-http/actions)
To the new scheme, this:
[![Build Status](https://img.shields.io/github/actions/workflow/status/pinojs/pino-http/ci.yml?branch=master)](https://github.com/pinojs/pino-http/actions)
---
Shield.io introduced a breaking change in their badge URL scheme. This changes the badge's URL to reflect this change.
Fixes badges/shields#8671
=> Fix CI badge URL

README.md, index.d.ts, index.test-d.ts
=> Fix: #289 add documentation and typescript definitions for res.log

logger.js, test/test.js
Hello!
I am the author of [pino-web-hook](https://getpino.io/#/docs/transports?id=pino-slack-webhook).
I am using the NestJS framework, and I wanted to display the `pinoHttp` property, thinking that the main function of `nestjs-pino` is Middleware that connects `pino-http`.
```
LoggerModule.forRoot({
pinoHttp: {
customProps: (req, res) => ({
context: 'HTTP',
}),
},
}),
```
However, I found the following bug, and also found out that there is an issue https://github.com/pinojs/pino-http/issues/216.
I tried the following to solve this problem.
1. I tried to use [onchild-function](https://github.com/pinojs/pino/blob/master/docs/api.md#onchild-function), but stopped because the instance given as a parameter was a logger instance that could be known outside of OnChildCallback.
```js
+ …
```
=> fix: twice customProps

index.d.ts, index.test-d.ts
Fixes #294
The typings on the various instances of `IncomingMessage` and `ServerResponse` are too strict when coupled with Express and Fastify `Request` instances that have been extended for custom properties. This loosens them up by allowing the main `pino` instance to be supplied a generic of the Request and Response interfaces that you use in your application.
Here it is in action:
And before without this generic, TS doesn't recognize our `project` property being on our Express `Request` object:
=> feat(ts): loosening up the IncomingMessage and ServerResponse typings

test/test.js
https://github.com/nodejs/node/pull/45597/files#diff-2464899ab38c61dd42654fdb9658c75989cb6883b9c9d76613872a12d3fe2780R1036 introduces a requirement that all incoming requests must have a `Host` header included. This is a breaking change in Node v20 that affects our test suite, and blocks #300. The change in this PR fixes it.
=> Fix tests on Node 20

.github/workflows/ci.yml, package.json
Hello everyone!
This PR is referencing this [issue](https://github.com/pinojs/pino-http/issues/299).
Quick question, should I leave `"pino-std-serializers": "^6.0.0"` like this? Or do we expect a major release after the update for v9?
Thank you in advance!
@jsumners
=> Updating for v9: update dependencies and CI

index.d.ts, index.test-d.ts
**Issue**
```
import { pinoHttp } from 'pino-http';
const httpLogger = pinoHttp({
customLevels: {
log: 20,
},
});
const logger = httpLogger.logger;
function f(level: 'warn' | 'info' | 'log', message: string): void {
logger[level](message);
}
```
This code is correct but currently throws a `ts(7053) : Element implicitly has an 'any' type` because TS can't see the custom level added in the configuration.
=> fix: Pino options have a generic type

index.d.ts, index.test-d.ts
the type variable of the logger should be the custom levels type
since a recent change in pino types (https://github.com/pinojs/pino/pull/1858)
fixes #313
cc @UndefinedBehaviour
=> fix: type variable for Logger

index.d.ts, index.test-d.ts, package.json
CustomLevels from pino parent instance should be passed through TypeScript variables.
Fixes #317
=> fix: TypeScript for CustomLevels on parent pino instance

.github/workflows/ci.yml, logger.js, test/test.js
=> fix: #308 include req.readableAborted flag to defaultSuccessfulRequestMessageProvider

logger.js, test/test.js
Similar to issue #199, this PR adds the responseTime argument to the custom errorMessage callback to provide more informative error logs.
=> feat: added responseTime argument to the custom errorMessage callback

README.md, index.d.ts, index.test-d.ts, logger.js, test/test.js
Applies similar logic as `quietReqLogger` to determine which logger instance to use.
Fixes #235
=> feat: add quietResLogger option

logger.js, test/test.js
The code failed to use `useLevel` when the custom level was, for example, camel-cased. 
I updated the test to reflect this occasional scenario and removed the unnecessary transformation of the log level.
=> fix: allow using non-lowercased custom levels

index.d.ts, index.test-d.ts
Fixed an issue where useLevel and customLogLevel Options parameters wouldn't accept CustomLevels.
=> fix: allow CustomLevels in useLevel and customLogLevel

logger.js, test/test.js
Closes https://github.com/pinojs/pino-http/issues/361.
=> feat: make check for allLogs more explicit
